### ISSUE TITLE
Issue Template Update

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#105]
### Outline the Issue

- [ ] Is the issue a bug?
- [ ] Is the issue a typo?
- [ ] Is the issue a proposed new feature?

### Describe the Issue

https://raw.githubusercontent.com/FreeCodeCampOKC/fccokc_web/master/ISSUE_TEMPLATE.md
Enhancement should an issue type option.
It would also be good to ask questions to help the project maintainers select the labels and assignee.

### Possible Solution

Add `- [ ] Is the issue an enhancement?` under `### Outline the Issue`.
Add a question for whether this might be a good first issue.
Add a question for whether the level is beginner/intermediate/advanced/unknown.
Add a question for whether the issue creator plans to work on the issue.

**Comment by mattstub** [comment]
I'm going to go ahead and take this and clean up issues we discussed yesterday as well
