### ISSUE TITLE
"Resolves" in Pull Request Template

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#106]
### Outline the Issue

- [ ] Is the issue a bug?
- [ ] Is the issue a typo?
- [ ] Is the issue a proposed new feature?

### Describe the Issue

In the pull request template, `Resolves #` marks the related issue as resolved when the pull request is closed, and that's not always the intended behavior.
https://github.com/FreeCodeCampOKC/fccokc_web/blame/master/PULL_REQUEST_TEMPLATE.md#L9

### Possible Solution

Make it clearer in the instructions to add the issue number after "Resolves #" if this completes the issue and to use "Updates #" for an on-going issue (like #4).

**Comment by stu7** [comment]
@kacollins I can try my hand at this one next, exposure working on that new template?
