### ISSUE TITLE
Add link to Techlahoma's Welcome Guide to Slack

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#108]
### Outline the Issue

- [ ] Is the issue a bug?
- [ ] Is the issue a typo?
- [ ] Is the issue a proposed new feature?

### Describe the Issue

Techlahoma's Welcome Guide to Slack has lots of good information about using Slack.

### Possible Solution

Add a link to https://www.techlahoma.org/news/2017/10/10/slack-welcome-guide on slack.html under "Learn more about Techlahoma's Slack:"

**Comment by stu7** [comment]
@kacollins  I'll work on this one, but it looks like there's already a link there. Should i find a different one? 
@kacollins Thanks for the clarification.
