### ISSUE TITLE
Add information about other Slack channels

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#109]
### Outline the Issue

- [ ] Is the issue a bug?
- [ ] Is the issue a typo?
- [ ] Is the issue a proposed new feature?

### Describe the Issue

It would be helpful to mention some other channels in Slack and their purpose, such as #announcements, #tech-talk, #random, #javascript, and #jobs.

**Comment by CoderAJ7470** [comment]
I'll work on this one

**Comment by mattstub** [comment]
Awesome! thanks @CoderAJ7470
