### ISSUE TITLE
Social icons for contact page

### ISSUE THREAD

**Issue by dashcraft** [FreeCodeCampOKC/fccokc_web_legacy#11]
Can we get some flat black social icons for the links to our contact information on the contact us page? That would be great!

**Comment by skyth3r** [comment]
I could try doing this for you. Just to confirm are you taking about the about page with the 'contact us' section at the bottom of the page?

**Comment by mattstub** [comment]
I actually just need to send in a pull request have these icons completed

**Comment by skyth3r** [comment]
Ok, I'll work on some of the other issues then
