### ISSUE TITLE
Update first-timer info page

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#128]
### What is the Issue?

- [ ] Is the issue a bug?
- [ ] Is the issue a proposed new feature?
- [x] Is the issue an enhancement?

### Describe the Issue

Resources link is not correct on mobile nav bar, and wording could use some improvement.

### Possible Solution

On firsttimers.html, fix the resources link, and run the wording on the page through hemingwayapp.com.

### Would this be a good first issue?

- [x] Yes
- [ ] No

### What is the difficulty level of this issue?

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced
- [ ] Unknown

**Comment by ezrahnyanat** [comment]
@kacollins My first contribution! I fixed the resources link and after running the page through hemingway, I reworded it to hopefully read more concise.
