### ISSUE TITLE
No Navigation to First Timers Page

### ISSUE THREAD

**Issue by mattstub** [FreeCodeCampOKC/fccokc_web_legacy#131]
### What is the Issue?

- [x] Is the issue a bug?
- [ ] Is the issue a proposed new feature?
- [ ] Is the issue an enhancement?

### Describe the Issue

Currently I can not locate a link to our *First Timers* Page, we need some secondary navigation for people to reach this page.

### Possible Solution

I believe something in the opening paragraph of the index page that could link people to this page would be acceptable.

### Would this be a good first issue?

- [x] Yes
- [ ] No

### What is the difficulty level of this issue?

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced
- [ ] Unknown

### Do you plan to work on the Issue?

No

**Comment by esquith** [comment]
Hi, I would like to take this

**Comment by mattstub** [comment]
@esquith awesome! let us know when you've got a PR to review! thanks!
