### ISSUE TITLE
LinkedIn Group

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#133]
### What is the Issue?

- [ ] Is the issue a bug?
- [x] Is the issue a proposed new feature?
- [ ] Is the issue an enhancement?

### Describe the Issue

We need a link to our LinkedIn group: https://www.linkedin.com/groups/12086660

### Possible Solution

Add a link to the Contact section on the About page.

### Would this be a good first issue?

- [x] Yes
- [ ] No

### What is the difficulty level of this issue?

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced
- [ ] Unknown

**Comment by membrq** [comment]
Can I claim?
