### ISSUE TITLE
Slack Clarifications

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#136]
### What is the Issue?

- [ ] Is the issue a bug?
- [ ] Is the issue a proposed new feature?
- [x] Is the issue an enhancement?

### Describe the Issue

The order of the information in the last two sentences in the first paragraph on the Slack page should be reversed, so that slack.techlahoma.org is mentioned before techlahoma.slack.com. Also, mention that you need to create an account for the Techlahoma Slack separate from any other Slack accounts that you might already have.

### Would this be a good first issue?

- [x] Yes
- [ ] No

### What is the difficulty level of this issue?

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced
- [ ] Unknown

**Comment by kaykay1424** [comment]
I can take care of this.

**Comment by kacollins** [comment]
That would be great!
