### ISSUE TITLE
Resources page styling

### ISSUE THREAD

**Issue by dashcraft** [FreeCodeCampOKC/fccokc_web_legacy#138]
### What is the Issue?

- [x] Is the issue a bug?
- [ ] Is the issue a proposed new feature?
- [ ] Is the issue an enhancement?

### Describe the Issue

Currently, the icon for the dropdowns on resources are different sizes when down caret vs right caret.

### Possible Solution

Possibly decrease the size of the carets to make it fit the UI better, add some
padding left to the title of the dropdown and give the icons a minimum width, 
so that when flipping between the two it won't jump around.

### Would this be a good first issue?

- [ ] Yes
- [x] No

### What is the difficulty level of this issue?

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced
- [ ] Unknown

### Do you plan to work on the Issue?

I am going to be leaving this to contributors.

### Mentions

@CarsonMcKinstry @mattstub let's see if we can get this taken care of, i'll be opening up the advanced website this weekend.

**Comment by linuxuser07** [comment]
I have a question for this, I changed the attribute of the min-icon and max-icon
so for the min-icon font-size: .92em; and for the max-icon: font-size: 1em;

I'm not sure if that is the solution needed for this.

**Comment by dashcraft** [comment]
Can you post a screenshot?

**Comment by linuxuser07** [comment]
![arrows](https://user-images.githubusercontent.com/4961375/37752545-9f478d54-2d66-11e8-833c-f87e7a6cf008.png)
![code](https://user-images.githubusercontent.com/4961375/37752546-a1f36dfc-2d66-11e8-9bac-0ce96aca2a0d.png)
Here you go

**Comment by linuxuser07** [comment]
Also if I force the padding on it to the right, the title stops moving and only the arrow moves, sorry for the late reply. 

``#toggle-youtube + label h2::before {
  content: attr(min-icon);
  font-family: "FontAwesome";
  font-size: .92em;
  padding-right: 7px;

}
#toggle-youtube:checked + label h2::before {
  content: attr(max-icon);
  font-family: "FontAwesome";
  font-size: 1em;
  font-size: .92em;
  padding-right: 0px;

**Comment by dashcraft** [comment]
Do you have a picture of the adjusted padding? Ideally we don't want the title to move because of the width of the icon, we only want the icon to change.

**Comment by dashcraft** [comment]
Looking good so far though!

**Comment by linuxuser07** [comment]
Can I claim this issue as Mine so I can do it. 

THank you

**Comment by dashcraft** [comment]
Yeah, no bigs

**Comment by linuxuser07** [comment]
Ok I think I got it, I added the padding and also change the size of the carets. 
Please let me know if that still looks off thank you 

`#toggle-youtube + label h2::before {
  content: attr(min-icon);
  font-family: "FontAwesome";
  font-size: .92em;
  padding-right: 9px;
}
#toggle-youtube:checked + label h2::before {
  content: attr(max-icon);
  font-family: "FontAwesome";
  font-size: 1em;
 padding-right: 0px;
}`
![image](https://user-images.githubusercontent.com/4961375/37870519-bb0a09ac-2f9d-11e8-8bdc-308aaa97f0c4.png)

**Comment by dashcraft** [comment]
Love it!
I will see if we can get it merged by the guys sometime here shortly!
Great work!

**Comment by dashcraft** [comment]
please submit it as a pull request

**Comment by linuxuser07** [comment]
Done
