### ISSUE TITLE
Remove 'Blog' link in the navbar

### ISSUE THREAD

**Issue by chris-tse** [FreeCodeCampOKC/fccokc_web_legacy#157]
### What is the Issue?
- [ ] Is the issue a bug?
- [ ] Is the issue a proposed new feature?
- [x] Is the issue an enhancement?

### Describe the Issue
The FCCOKC Medium blog got taken down for unknown reasons. It has also not been active in a long time. The link in the navbar will need to be removed.

If we have enough members to get a blog going (which is not likely), we can consider using a simple static site generator for blogs in the future.

### Solution
Simply removing [this line](https://github.com/FreeCodeCampOKC/fccokc_web/blob/master/docs/index.html#L51) should do the trick. Make sure to repeat this on all pages!

**Comment by KafilatAdeleke** [comment]
I'm currently working on this.
