### ISSUE TITLE
Create a "Hall of Fame" page

### ISSUE THREAD

**Issue by chris-tse** [FreeCodeCampOKC/fccokc_web_legacy#158]
### What is the Issue?

- [ ] Is the issue a bug?
- [x] Is the issue a proposed new feature?
- [ ] Is the issue an enhancement?

### Describe the Issue
~~While running and moderating an entire mentoring system is unfeasible, we can still help point folks in the right direction if they are seeking mentors or are wanting to be a mentor.~~

~~Let's create a new page where we can have a list of mentors displayed with contact info of their choice and what skills they are able to mentor with. We could also display a list of mentees who are looking as well.~~

~~To add yourself as a mentor (or mentee) it would be through a PR system so that we can, at minimum, have some preliminary vetting for safety purposes.~~

### Possible Solution
~~1. Remove the "Projects" link from navbar~~
~~2. Adding a new "Mentoring"(? name can be discussed) link in its place~~
~~3. Have that link to a new mentoring.html page.~~
    ~~- I don't have very strong opinions on the layout of the page. It could be a simple two column list with mentors on one side and mentees on the other. Or we could go a bit fancier and make a card-based layout.~~

See [this comment for updated details](https://github.com/FreeCodeCampOKC/fccokc_web/issues/158#issuecomment-710702508)

**Comment by bedbathburritos** [comment]
I'm gonna try to take a stab at this one. :)

**Comment by chris-tse** [comment]
Go for it

**Comment by chris-tse** [comment]
As discussed on Slack, we're going to modify what we're going with. Let's make a "Hall of Fame" for helpful folks around Techlahoma. Some high level ideas might be a page with a grid of cards of these people with some links to things like their Twitter, Github, or Slack username. Will edit this post after some brainstorming on Slack with more concrete ideas.

**Comment by alex-code4okc** [comment]
Closed with #161 and #162
