### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#19]
Add information about what Slack is and how to get to the freecodecamp channel in Slack

**Comment by stu7** [comment]
There is already some Slack info with a link on the index.html page. Are you looking for expansion upon what is already there?

**Comment by kacollins** [comment]
Yes, it would be great to expand on what Slack is, how we use it, how to sign up, and how to join the freecodecamp channel once you're in Slack. This will probably be on a new page and involve some screenshots, so it is probably a more advanced issue, not a beginner one.

**Comment by mattstub** [comment]
I believe this issue has been resolved?

**Comment by Jason9199** [comment]
It has with pull request 42.

**Comment by kacollins** [comment]
http://www.fccokc.com/slack.html

This page is really helpful. Great job, @Jason9199!
