### ISSUE TITLE
Twitch link on about us page

### ISSUE THREAD

**Issue by dashcraft** [FreeCodeCampOKC/fccokc_web_legacy#2]
On the about us page, I think that having this
![image](https://user-images.githubusercontent.com/11915975/28756084-406b4c0e-752d-11e7-9b93-39b31eeda946.png)

as a link to twitch.tv/techlahoma would be a great idea.
Feel free to make these changes on your fork and submit a pull request, referencing this issue!

**Comment by kacollins** [comment]
Add a link on any other references to Twitch on the website while you're at it!

**Comment by mattstub** [comment]
Would like to take this on if no one else has started on it, noted a couple spots to update the link to Twitch.

Also would you like the About Us to mirror the starspace46 link like the Main Page does?
