### ISSUE TITLE
Free Code Camp

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#20]
On the About page, add a link to freecodecamp.com and remove the references to Node and Angular. Angular is no longer in the curriculum, and Node is not really a major part.

**Comment by mattstub** [comment]
I believe this issue was closed out on Pull Request 29, don't know why it's showing open still, @CarsonMcKinstry?

**Comment by kacollins** [comment]
Looks like it's done. Good job, @MasonT3!
