### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#21]
Add pictures from past meetups so people know what to expect

**Comment by Jason9199** [comment]
Are there any pictures such as the ones described here available already that we can use? Meetup.com seems to be lacking these.

**Comment by kacollins** [comment]
Part of this issue might be going to the meetups and taking pictures. It would be great to post some on our Meetup and Facebook pages too.

**Comment by mattstub** [comment]
Seen lots of pictures taken recently, hopefully someone will find the time to get them uploaded and pushed over here.

**Comment by kacollins** [comment]
Where should people put pictures that they would like to share?

**Comment by mattstub** [comment]
that's a good question.. Do we want to do a sidebar that illustrates some thumbnails and leads to a modal? or a carousel or just a static picture page?

**Comment by alex-code4okc** [comment]
Closed until pandemic is over. 🤞🏽
