### ISSUE TITLE
Twitch Stream

### ISSUE THREAD

**Issue by CarsonMcKinstry** [FreeCodeCampOKC/fccokc_web_legacy#23]
## RESEARCH NEEDED

Since we stream on Twitch most Sundays, it would be nice to see our stream simulcast here as well, if possible (it may not be possible since we stream through the Techlahoma account).

**Comment by CarsonMcKinstry** [comment]
Found a resource that may be useful, if someone wants to tackle this:

https://dev.twitch.tv/docs/v5/guides/embed

**Comment by Jason9199** [comment]
That link is broken. I believe this is probably the page you were trying to link to. https://dev.twitch.tv/docs/embed
