### ISSUE TITLE
Twitch Recordings

### ISSUE THREAD

**Issue by CarsonMcKinstry** [FreeCodeCampOKC/fccokc_web_legacy#24]
Display the Free Code Camp specific videos from Twitch. Should be watchable without going to Twitch. It would be nice to have the list of videos, the currently being played video can be swapped out for.

**TIP:** Take a look the sharing options for videos on Twitch.

**Resource:** https://www.twitch.tv/techlahoma/videos/all

**Comment by CarsonMcKinstry** [comment]
Hint: A JS library or framework could be used to accomplish this.

**Comment by Jason9199** [comment]
The biggest challenge I see with this is since they're listed on the techlahoma channel along with several other non fcc videos, I don't know if there's a way to filter out only the fcc videos and show those and exclude all the others.

**Comment by kacollins** [comment]
Ideally, the videos for our group would have "Free Code Camp" (with or without spaces) and "OKC" in the title. This isn't always the case, but that might be the best way to start.

**Comment by Jason9199** [comment]
From the Twitch docs it appears you can organize videos on a channel into Collections, which can then be retrieved via the API. If we can put the FCC videos in a collection, I can retrieve them and make them available on a page.

https://help.twitch.tv/customer/portal/articles/2752733-how-to-use-collections?b_id=14444
https://dev.twitch.tv/docs/embed#non-interactive-inline-frames-for-live-streams-and-vods
https://dev.twitch.tv/docs/v5/reference/collections#get-collection

**Comment by kacollins** [comment]
I created a collection called `freeCodeCamp OKC` for this.
