### ISSUE TITLE
YouTube Playlist

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#25]
Add link to our YouTube playlist: https://www.youtube.com/watch?v=2fJkaSrMAOs&list=PLdW0ayjzW_LC3r4TIg08APaJlgtI9t8BH

**Comment by kasifrass** [comment]
I would like to take this (so I can get acquainted with GitHub).

**Comment by CarsonMcKinstry** [comment]
@kasifrass Go for it! Once you're done don't forget to open a pull request!

**Comment by julistanley** [comment]
I'll give this a shot if that's okay since @kasifrass hasn't opened a pull request yet.
