### ISSUE TITLE
Break out Dir folders

### ISSUE THREAD

**Issue by dashcraft** [FreeCodeCampOKC/fccokc_web_legacy#3]
The current folder structure is:
![image](https://user-images.githubusercontent.com/11915975/28756151-66b7915a-752e-11e7-9a2a-6d9f0e2fa74d.png)

> index.html
> ./blog/index.html
> ./about/index.html
> ./projects/index.html

This should be flat for now, for example:
index.html
aboutus.html
projects.html
blog.html

**Comment by mattstub** [comment]
Daniel, to make sure I understand this issue correctly you are just wanting to remove the subfolders for the other pages, place all page content in the main folder and rename files accordingly, then correct the links/file paths appropriately?

**Comment by dashcraft** [comment]
Yes, you are correct.

Also, they need to be moved to the /dist folder

Right now there are duplicates
