### ISSUE TITLE
GitHub Repo

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#35]
Add a link to this github repo and information about how to contribute on the projects page

**Comment by skyth3r** [comment]
I can do that if you want. Where would you want this link? On an existing page (such as the about page) or as a new page?

**Comment by kacollins** [comment]
What about just adding a short sentence to the Projects section on the index page? Something like `You can contribute to this website on GitHub!` The website will also be listed on the Projects page as part of another issue, so it doesn't need to be added there right now.

**Comment by skyth3r** [comment]
Ok sure, I'll hyperlink the 'Github' bit then as well

**Comment by stu7** [comment]
I had this one done awhile ago for the projects page, but due to the complications with my local repo, it needs be pushed from a new branch. Can I still open a pull request for it?

**Comment by Jason9199** [comment]
@stu7 Go for it!

**Comment by stu7** [comment]
Ok

**Comment by mattstub** [comment]
resolved with PR#75
