### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#37]
Add a CONTRIBUTING.md markdown file that explains how to contribute to this repo.

**Comment by skyth3r** [comment]
I can try and do this. Might need to look over some examples first though.

**Comment by kacollins** [comment]
It looks like this has been done: https://github.com/FreeCodeCampOKC/fccokc_web/pull/47

**Comment by kacollins** [comment]
Good work, @Jason9199!
