### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#38]
Add a link to the Facebook group: https://www.facebook.com/groups/free.code.camp.oklahoma.city

**Comment by mattstub** [comment]
Do we want a stand alone link, or should his incorporate with #11 by adding a list of social icons somewhere?

**Comment by kacollins** [comment]
I'm thinking this is separate. I would like to see a list of links in addition to the icons. Adding the Facebook group to the Contact section on the about page would probably make the most sense.

**Comment by kacollins** [comment]
The link would go at the bottom of this page, at the end of the Contact section: http://www.fccokc.com/about.html

This would be an ideal task for someone who has never created a pull request before!

**Comment by julistanley** [comment]
I have this done! Just trying to figure out how to make the pull request now :)
