### ISSUE TITLE
Meetup Recaps

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#39]
Add summaries of what we learned at past meetups on the blog page

**Comment by Jason9199** [comment]
The CodeForOKC site from which this was cloned after sends the link for their blog to medium.com https://medium.com/code-for-okc Is this our intention for our blog, and if so is this account set up yet?

**Comment by kacollins** [comment]
I don't think we have decided for sure yet, but I believe that's the plan and the account is not set up yet.

**Comment by stu7** [comment]
@kacollins @dashcraft  I think I could start working on this in steps/stages, but I'm not sure where to begin with or what, exactly. Could you provide some feedback as to where/how you'd like to begin tackling this issue?

**Comment by mattstub** [comment]
https://www.meetup.com/FreeCodeCampOKC/events/past/ this would be a good place to start, each meetup has a short intro about what we are talking about, I think this is kind of what @kacollins had in mind. Would like it to be more in depth if possible by people who attended some of these meetups

**Comment by mattstub** [comment]
https://refreshokc.org/meetups/ this might also be a good place to get some inspiration from as well.

We were thinking just a single page much like https://medium.com/tulsa-ux, to make multiple entries as meetups happen. Both links have good examples of the what we are looking for content wise.

(edit: add tulsa-ux)

**Comment by kacollins** [comment]
@CarsonMcKinstry got us set up on [Medium](https://medium.com/freecodecamp-okc/about)! Now we just need some blog posts! Join us in the #fccokc-blog channel in Slack if you have any questions or want to discuss this more.

**Comment by chris-tse** [comment]
Closing due to RIP medium blog for unknown reasons.
