### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#40]
Add summaries and links for our GitHub repositories to the projects page

**Comment by ashwani99** [comment]
@kacollins I want to work on this. Can you provide the links that should be added? Are all these projects [here](https://github.com/FreeCodeCampOKC) should be added?

**Comment by kacollins** [comment]
Yes, those are the projects to list. `presentation-slides` isn't a project exactly, and `react-course` hasn't gotten off the ground yet, so it might be better to not include those two.

**Comment by ashwani99** [comment]
@kacollins Does it look good? Can you please review it?
