### ISSUE TITLE
Job Fair

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#43]
Create an entry on the blog page about our upcoming job fair and how to prepare for job fairs.

**Comment by Jason9199** [comment]
The CodeForOKC site from which this was cloned after sends the link for their blog to medium.com https://medium.com/code-for-okc Is this our intention for our blog, and if so is this account set up yet?

**Comment by kacollins** [comment]
The intention for this blog entry was to have a simple HTML page linked from http://www.fccokc.com/blog.html.

**Comment by kacollins** [comment]
This will probably be on hold until the next job fair or we get the blog set up.

**Comment by chris-tse** [comment]
Closing outdated issue
