### ISSUE TITLE
Slack Page Updates

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#49]
In the first paragraph on the slack.html page, one of the links should go to https://techlahoma.slack.com/ instead of http://slack.techlahoma.org/:

`For example, you can access the Techlahoma Slack by visiting https://techlahoma.slack.com/. If you do not yet have an account for the Techlahoma Slack, you can request one at http://slack.techlahoma.org/.`

It would also be good to mention that the code of conduct applies in Slack. A link to Techlahoma's information about Slack at https://www.techlahoma.org/spaces would be great.

A lot of people don't know that Slack has desktop and mobile apps, so adding information about them would be helpful.

**Comment by ghost** [comment]
I'd like to help with this!

**Comment by kwinzig** [comment]
Hey :) Can I work on this?

**Comment by kacollins** [comment]
Looks like @thegreyelephant commented first, @kwinzig. We have plenty of other issues, or you can create your own!

**Comment by GeekyShiva** [comment]
@kacollins Please review and merge as i have made a PR with all the changes requested.

Thanks
