### ISSUE TITLE
Volunteer Links

### ISSUE THREAD

**Issue by kacollins** [FreeCodeCampOKC/fccokc_web_legacy#50]
Add a link to the twitter accounts for Ava and Brent on the About page:
https://twitter.com/avasond
https://twitter.com/Brent_Shambaugh

This would be an ideal task for someone who has never created a pull request before!

**Comment by nab0310** [comment]
@kacollins I'll take a look at this!

**Comment by ashwani99** [comment]
@kacollins Can I take this?

**Comment by kacollins** [comment]
@ashwani99, it looks like @nab0310 got it first. We have several other issues that you can work on!

**Comment by nab0310** [comment]
I'll open a PR tomorrow for it!
