### ISSUE TITLE
Page for "Setting up your dev environment"

### ISSUE THREAD

**Issue by CarsonMcKinstry** [FreeCodeCampOKC/fccokc_web_legacy#61]
Need a resource page for newcomers to show how to set up a basic dev environment

- install node
- install a terminal if they don't have it
- install a text editor
- install a decent browser (Chrome is recommended often)

**Comment by brycejech** [comment]
I can take this one. Have a couple questions.

1. Windows, macOS, and every variety of Linux I've ever used comes with a terminal by default. I've never had to install one and doubt the case that anyone may need instructions for this. Unless you are talking about installing an SSH client. If that is the case I can add some instructions for installing PuTTY. Most Linux distros and macOS come with SSH client by default.
1. I think we should recommend or at least also give instructions for installing Firefox.

**Comment by Jason9199** [comment]
@brycejech My $.02 regarding your first point is you might include references to popular terminal programs, like iTerm2 for Mac and Cmder for for Windows. While you are correct every OS comes with their own version of a command line by default, there are a lot of niceties and options that come from some 3rd party programs like the ones I suggested that will not always be available using the built in option. So maybe mention the built in command line and then offer alternatives if someone would rather use those.

Regarding point two, it's probably a good approach to provide links to both Chrome and Firefox. Which one that is recommended is obviously a subjective opinion, one that people often have lively arguments about. I would suggest we may stop short of recommending a browser. Ultimately we have to develop with all browsers in mind, which is an unending source of frustrations for all web developers.

**Comment by brycejech** [comment]
Ha! Re-reading my second point, it does look opinionated. I certainly don't want to start any flame wars. Agree that we should stop short of making a recommendation, will add instructions for both.
