### ISSUE TITLE
Slack page missing navbar on mobile

### ISSUE THREAD

**Issue by Jason9199** [FreeCodeCampOKC/fccokc_web_legacy#62]
When the site is viewed on mobile every page has a functional navbar fit for mobile screens except the slack.html page. Currently when you go to that page the navbar disappears. 

We need to update the Slack page to display the mobile navbar just like pages on the rest of the site.

**Comment by brycejech** [comment]
Sent my initial PR to the wrong repo. Should be fixed now.
