### ISSUE TITLE
Link to Slack Page on About Page

### ISSUE THREAD

**Issue by mattstub** [FreeCodeCampOKC/fccokc_web_legacy#68]
Before we merged in the social icon change, the original link to the slack sign-up page had a tooltip link that lead to a page showing how to utilize slack. Could someone add this tooltip link back to the about page, on the line advising visitors how they can contact us?

If you are looking for direction with this issue, take a look under the chat section of the index.html page

**Comment by brycejech** [comment]
@mstub just to clarify, are you wanting another small question mark icon added next to the slack icon on the about page that links to the slack.html page? (similar to the "?" icon on index.html)

Not to be too opinionated (and unsure if this has already been discussed elsewhere), but I think that we should remove this question mark icon altogether and insert additional language that links to the slack.html page. Beginners may not see it or even know that they can click on it. It's very small and not super clear that it takes you to a page describing how to use slack. I propose that we update the index.html page Chat section to read as follows: 

We also have a [Slack](http://slack.techlahoma.org/) room where we can have real-time discussions and offer help and advice when needed. Not sure how to use slack? Check out our [Slack page](http://fccokc.com/slack.html) for more info.

**Comment by kacollins** [comment]
I agree!

**Comment by mattstub** [comment]
I was meaning for it to go on the verbiage where it says "you can contact us via..." not on the icon itself. However I see no problem with the way you have proposed.

**Comment by brycejech** [comment]
I think both are ok. I can update the language on the index.html page as described above. Then insert the same language after the "You can contact us via..." string on the about.html page. Sound good? Alternatively, I can put the language below the social icons on the about page, it may look even better just blow it, that way we can leave that colon ":" and leading text in place. Thoughts?

**Comment by mattstub** [comment]
I don't think we would need to use the same verbiage on the about page, probably just add a link to the slack information page where it says "You can contact us via e-mail, Facebook, Twitter, or Slack:"?
