### ISSUE TITLE
About us section

### ISSUE THREAD

**Issue by dashcraft** [FreeCodeCampOKC/fccokc_web_legacy#7]
We should change the organizers and volunteers to show the following

Organizers
Daniel Ashcraft (co-organizer)
Kimberly Collins (co-organizer) 
Carson McKinstry (co-organizer)
Jennifer Gladney (co-organizer)

Volunteers
Ava Pipher
Brent Shambaugh

**Comment by dashcraft** [comment]
They should also be clickable links to the following (we can add the others as we find them)

Daniel Ashcraft (co-organizer) link: https://github.com/dashcraft
Kimberly Collins (co-organizer) link : https://github.com/kacollins
Carson McKinstry (co-organizer) link: https://github.com/CarsonMckinstry
Jennifer Gladney (co-organizer) link: 

Ava Pipher
Brent Shambaugh

**Comment by mattstub** [comment]
I believe the current page shows Jack Kinsey as an organizer, do we want to remove him at this time?
Also, the current link for Jennifer Gladney points to her Meetup Profile, do we want to leave this in place?

I was thinking of splitting up the Organizers and Volunteers with separate subsections and headings, is this the direction you were thinking? -- Disregard this question, I see it broken out in the original comment (edit)

**Comment by dashcraft** [comment]
Yes, that was copied from the meetup.com profile which isn't the most up to date. We are correcting that now.

If we do not have any website/contact info, we can use the meetup profile that's fine. There are some, like brent, with whom we do not have any information on. Also, you want to add yourself and your contact info and name on the contributions section. That section is on another GH issue.

**Comment by CarsonMcKinstry** [comment]
Solved by #13
