### ISSUE TITLE
Mobile Nav Bar not listing Twitch

### ISSUE THREAD

**Issue by mattstub** [FreeCodeCampOKC/fccokc_web_legacy#71]
The twitch page is not listed on the mobile navigation bar, a list element needs to be added for this page to mirror the main navigation bar. 

When looking at this issue, make sure that both navigation bars are uniform across all respective pages. If you have any questions please ask!

**Comment by skyth3r** [comment]
Fixed these issues. Nav bars are uniforms across all the pages.
