### ISSUE TITLE
Introduction of Bootstrap in PR #67 changed font-size and font-family on index.html

### ISSUE THREAD

**Issue by brycejech** [FreeCodeCampOKC/fccokc_web_legacy#74]
@mstub @Jason9199 
I believe the introduction of bootstrap with PR #67 changed the `font-size` and `font-family` on the home page. Not sure if that was intentional or not, but it no longer conforms to the rest of the site. You can `checkout` 6efc2631de6bd64e1e6b32472e0c2eb496c67416 to see what it was just before the introduction of bootstrap.

**Comment by mattstub** [comment]
@brycejech this was definitely not by design, haha. I noticed this morning that I was going to have to re-work the parking modal that utilizes bootstrap or figure out what the clash is, unless you are bored and wanting to look into it
