### ISSUE TITLE
Code Of Conduct

### ISSUE THREAD

**Issue by dashcraft** [FreeCodeCampOKC/fccokc_web_legacy#81]
We should Copy the Techlahoma Code of Conduct and include it in this repositories Code of conduct. If you click on insights, then the heart symbol (for community) it will outline some helpful metrics that your repo should embrace, to make the repo more friendly to the community.

**Comment by Jason9199** [comment]
Our README links to the Techlahoma Code of Conduct already.

**Comment by kacollins** [comment]
It looks like having a CODE_OF_CONDUCT.md is suggested:
https://github.com/FreeCodeCampOKC/fccokc_web/community/code-of-conduct/new
https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

**Comment by dashcraft** [comment]
Yeah as @kacollins said, one of the github community friendly guidelines says that a code of conduct for the repo itself is advised.
