### ISSUE TITLE
BUG: Issue & PR Templates

### ISSUE THREAD

**Issue by mattstub** [FreeCodeCampOKC/fccokc_web_legacy#86]
### Outline the Issue

- [x] Is the issue a bug?
- [] Is the issue a typo?
- [] Is the issue a proposed new feature?

### Describe the Issue

The checklist boxes are not displaying properly because the markdown is incorrect, can someone revise these two items with the proper syntax?

### Possible Solution

I believe this [guide](https://help.github.com/articles/about-task-lists/) will help show the correct syntax

**Comment by CoderAJ7470** [comment]
I'll go ahead and work on this one.
