### ISSUE TITLE
BUG: Social Icon Styling

### ISSUE THREAD

**Issue by mattstub** [FreeCodeCampOKC/fccokc_web_legacy#87]
### Outline the Issue

- [x] Is the issue a bug?
- [] Is the issue a typo?
- [] Is the issue a proposed new feature?

### Describe the Issue

When displaying the website in chrome, the social icon styles are not displaying properly, however they seem to work properly in firefox and safari. They are utilizing the anchor tag styling and showing up as a link instead of the defined black styling.

**Comment by Jason9199** [comment]
Can you be more specific? What about how they are displaying is improper?

**Comment by mattstub** [comment]
edited original comments for more information, below are some screenshots. The first is of the social icons showing up currently. The second is how the icons should be displaying.

![fcc social](https://user-images.githubusercontent.com/26757091/31401051-3761d020-adb7-11e7-8830-1424c702de8d.png)

![fcc social black](https://user-images.githubusercontent.com/26757091/31401225-e5ab89be-adb7-11e7-96a2-5e6680a0e323.png)

**Comment by mattstub** [comment]
upon some more investigating it appears the icons work once the window width has reached 600px, beyond that they appear blue.

**Comment by egkwong** [comment]
Question?  
what is the desired style for the social icons, black or #33a6b8? 
Always?
I tested with Chrome and firefox on linux, safari on mac, and chrome on Android. 
Results... There is a break point at 650px. black < 650px <  #33a6b8.
Looks like a quick fix let me know. I might do a pr tonight and turn it all black if nobody points me in another direction before then.

**Comment by mattstub** [comment]
@egkwong the intended styling is to always be black. The #33a6b8 is for other page links, but the intention of the social icons is to be black.

thanks for looking into this for us!
