### ISSUE TITLE
Code of Conduct Linking

### ISSUE THREAD

**Issue by mattstub** [FreeCodeCampOKC/fccokc_web_legacy#98]
### Outline the Issue

- [x] Is the issue a bug?
- [] Is the issue a typo?
- [] Is the issue a proposed new feature?

### Describe the Issue

This is not really a bug, but could someone revise the README.md to link to our CODE_OF_CONDUCT.md now?

**Comment by Goombac** [comment]
So do you want it to lead like the Contributing part? 

![image](https://user-images.githubusercontent.com/26773515/31571546-74546b32-b05a-11e7-8613-9f92cc2c874e.png)

Is this what you were thinking?

**Comment by mattstub** [comment]
yes, that is correct @jmerrill3 !
